### ISSUE TITLE
File list may be not completely loaded in some conditions

### ISSUE THREAD

**Issue by wolfpld** [filebrowser/filebrowser#1327] opened 2021-03-14 20:02 UTC
When grid view is used to display a list of files on screen resolutions larger than 1080p, the available files fit within the page. This makes the "infinite loading" mechanism break, as it seems to be activated only when the contents are scrolled down. In effect, the user is presented with incomplete list of files without any indication that there are more available.

This can be reproduced on smaller screens by reducing the browser zoom level.

**Comment by o1egl** [comment] 2021-03-15 08:55
Duplicate of https://github.com/filebrowser/filebrowser/issues/1238

**Closed as completed by o1egl** 2021-03-15 08:55 UTC
