### ISSUE TITLE
Any possible to show the thumbnail of files？

### ISSUE THREAD

**Issue by Chadwick97** [filebrowser/filebrowser#283] opened 2017-11-14 16:50 UTC
Showing the thumbnail of files such as videos and pictures is really helpful to manage files. Like h5ai [https://github.com/lrsjng/h5ai](url). Hoping to add this function on.
Thank you.

**Comment by hacdias** [comment] 2017-11-14 18:09
Duplicate of #128. Please vote there with a reaction or a comment, please 😄

**Closed as completed by hacdias** 2017-11-14 18:09 UTC
