### ISSUE TITLE
last modified show full time format

### ISSUE THREAD

**Issue by hailong1004** [filebrowser/filebrowser#1437] opened 2021-06-17 06:39 UTC
**Is your feature request related to a problem? Please describe.**

If I changed it many times a day ago, the display of "1 days ago" makes me feel more confused

**Describe the solution you'd like**

I want to see last-modified in full time format

**Describe alternatives you've considered**

Like Last-Modified in the HTTP Header, it displays : last-modified: Wed, 16 Dec 2020 17:37:20 GMT

**Additional context**

![image](https://user-images.githubusercontent.com/18435715/122344777-b9cacc00-cf79-11eb-80b3-1de12020f7d9.png)
![image](https://user-images.githubusercontent.com/18435715/122344891-da932180-cf79-11eb-97a5-5cec6d575e56.png)

**Comment by o1egl** [comment] 2021-06-22 08:56
Duplicate of https://github.com/filebrowser/filebrowser/discussions/1270

**Closed as completed by o1egl** 2021-06-22 08:56 UTC
