### ISSUE TITLE
Android browser PDF is not visible 

### ISSUE THREAD

**Issue by VinaySavla** [filebrowser/filebrowser#2082] opened 2022-08-07 18:41 UTC
**Description**
In Android browsers pdf's are not opening up. Showing the flash icon on the screen. 

**Expected behaviour**
The pdf should be opened in view mode

**What is happening instead?**
In Android browsers pdf's are not opening up. Showing the flash icon on the screen. 

**Additional context**
![IMG_20220808_001224](https://user-images.githubusercontent.com/71120627/183306206-a5cb68f9-a322-4dde-8388-cf865c2363cd.jpg)

**How to reproduce?**
Login on the portal using chrome/Edge using Android device and double click on any pdf file.

**Comment by o1egl** [comment] 2022-08-08 09:26
Duplicate of https://github.com/filebrowser/filebrowser/issues/1201

**Closed as completed by o1egl** 2022-08-08 09:26 UTC

**Comment by fmartinou** [comment] 2023-08-25 17:48
Hi,

I don't understand; both this issue and the issue #1201 are marked as closed whereas the bug is still present.
What's the status? Any plan to fix it?

Isn't possible to just have the Android browser to download the file instead of displaying the "This plug-in is not supported" screen?

**Comment by pierluigizagaria** [comment] 2024-05-17 13:39
Issue still persists
