### ISSUE TITLE
File upload with status pop-up window

### ISSUE THREAD

**Issue by hapylestat** [filebrowser/filebrowser#2093] opened 2022-08-21 18:04 UTC
**Is your feature request related to a problem? Please describe.**
-
During the file upload, especially large one the current upload progress is rather primitive and doesn't contain basic information like upload speed, estimated time, percentage. The top progress bar is not that much descriptive about what it even tracks.

**Describe the solution you'd like**
-
Add some "Upload manager" pop-up window, like in gdrive and add there:
- the progress bar with speed information
-  file/folder name to be uploaded
-  percentage
- estimated time*

**Describe alternatives you've considered**
-
none

**Additional context**
-
none

**Comment by o1egl** [comment] 2022-08-29 16:45
Duplicate of https://github.com/filebrowser/filebrowser/issues/1380

**Closed as completed by o1egl** 2022-08-29 16:45 UTC
