### ISSUE TITLE
Right click menu

### ISSUE THREAD

**Issue by alvaroaleman** [filebrowser/filebrowser#1329] opened 2021-03-14 21:33 UTC
One UX annoyance with filebrowser today is that it does not provide a rightlick menu. This leads to first needing to select the file, then moving the mouse to the top bar to do whatever you want to do. It would be much nicer to additionally have the actions in the top bar as right click menu, as that would save the need for the second mouse movement.

**Comment by o1egl** [comment] 2021-03-15 08:55
Duplicate of https://github.com/filebrowser/filebrowser/discussions/1031

**Closed as completed by o1egl** 2021-03-15 08:55 UTC
