### ISSUE TITLE
active shell in filebrowser web, then   I want active python shell. It didn't work

### ISSUE THREAD

**Issue by simzhangbest** [filebrowser/filebrowser#1064] opened 2020-08-15 01:59 UTC
![python-issue](https://user-images.githubusercontent.com/24918900/90303085-8cd30600-dedd-11ea-9956-6b8ba8577ca7.png)
sth like this, gdb , I'm using you system's shell to do some python work remotly. would you like help me or tell me how to do this, that I will be very grateful , thank you

**Comment by o1egl** [comment] 2020-08-16 09:49
At the moment shell is not interactive.

**Comment by o1egl** [comment] 2020-08-16 09:50
Duplicate of the #984

**Closed as completed by o1egl** 2020-08-16 09:50 UTC

**Comment by simzhangbest** [comment] 2020-08-16 14:38
thank you very much
