### ISSUE TITLE
Bug or feature: symbolic link to folders shown as files

### ISSUE THREAD

**Issue by ldesousa** [filebrowser/filebrowser#521] opened 2018-08-23 13:08 UTC
**Description**
Filebrowser shows symbolic links to folders as files.

**Expected behaviour**
Symbolic links to folders showing as folders.

**What is happening instead?**
Symbolic links shown as files

**Additional context**
Is this a glitch? Or is it made on purpose?

**How to reproduce?**
Create a symbolic link in the scope.

**Files**
-

**Comment by hacdias** [comment] 2018-08-30 07:00
Duplicate of #416. I updated the title of 416 because it wasn't very clear. Let's have this discussion there!

**Closed as completed** 2018-08-30 07:00 UTC
