### ISSUE TITLE
Clipboard Functionality Fails on Safari Browser (MacOS)

### ISSUE THREAD

**Issue by OleMantei** [filebrowser/filebrowser#3407] opened 2024-08-16 11:43 UTC
**Description**
The clipboard functions 'copyToClipboard' and 'copyDownloadLinkToClipboard' (frontend/src/components/prompts/Share.vue), intended to copy links to the clipboard, are not working as expected on Safari browsers, though they operate correctly on Google Chrome. This issue has been observed on the latest version of Safari, and it impacts user experience by preventing users from easily copying links.

**Expected behaviour**
When either clipboard button is clicked, the corresponding link should be successfully copied to the clipboard, allowing the user to paste it anywhere.

**What is happening instead?**
In Safari, clicking either clipboard button does not result in the link being copied. There is no error displayed on the UI, and the clipboard does not update with the new content.

**Additional context**
![Bildschirmfoto 2024-08-16 um 13 31 02](https://github.com/user-attachments/assets/ce92f5ce-6482-45ba-9699-b0e8eb4e47d2)
Safari: Version 17.2.1 (19617.1.17.11.12)
File Browser: 2.30.0

**How to reproduce?**
1. Navigate to the sharing overlay on the frontend.
2. Click either the "Copy to Clipboard" button for a regular link or the "Copy Download Link to Clipboard" button for a downloadable content link.
3. Observe the lack of success notification popup in Safari.
4. Attempt to paste the copied link elsewhere.

**Files**
Any folder or files.

**Comment by geozeke** [comment] 2024-09-09 10:44
This was highlighted in #3232, which has since been closed. It seemed fixed in a pre-release build, but it looks like the issue is back.

**Comment by ShowUNow** [comment] 2024-09-17 16:26
> This was highlighted in #3232, which has since been closed. It seemed fixed in a pre-release build, but it looks like the issue is back.
> 

Do you know which specific version that bug had been fixed? It's a little frustrating for me that I cannot copy the share link on my mobile devices in the 2.30v. Thank you!

**Comment by geozeke** [comment] 2024-09-17 16:40
Sorry, I'm not sure what version that was. I'm running filebrowser in Docker, and it's been a while since it worked. 

The pre-released build I mentioned was one that I built myself from a branch of the repository. I don't think Safari clipboard functionality has been working in production for quite some time.

**Comment by mylogon341** [comment] 2024-09-18 08:17
I also can confirm this is borked
Safari 17.6
File Browser 2.31.1

**Comment by KristjanPikhof** [comment] 2024-10-01 15:17
I can confirm that the feature is not functioning on iOS across multiple browsers, including Safari, Chrome, and Opera on iPhone. 
I am using latest Filebrowser version via Docker.

Screen record:
https://github.com/user-attachments/assets/0de849f8-3b09-4a27-889f-5a7aeff3b6e1

**Comment by ShowUNow** [comment] 2024-10-01 15:33
> I can confirm that the feature is not functioning on iOS across multiple browsers, including Safari, Chrome, and Opera on iPhone. 
> 
> I am using latest Filebrowser version via Docker.
> 
> 
> 
> Screen record:
> 
> https://github.com/user-attachments/assets/0de849f8-3b09-4a27-889f-5a7aeff3b6e1
> 
> 
> 
> 
You can copy the share link by using the http connection rather than https. I know it's not a good way but it's effective.

**Comment by KristjanPikhof** [comment] 2024-10-01 21:55
> > I can confirm that the feature is not functioning on iOS across multiple browsers, including Safari, Chrome, and Opera on iPhone. 
> > 
> > I am using latest Filebrowser version via Docker.
> > 
> > 
> > 
> > Screen record:
> > 
> > https://github.com/user-attachments/assets/0de849f8-3b09-4a27-889f-5a7aeff3b6e1
> > 
> > 
> > 
> > 
> You can copy the share link by using the http connection rather than https. I know it's not a good way but it's effective.

I attempted it, but my browser keeps redirecting me to HTTPS, making it unusable for me. It might be related to other server settings. For now, it would be great if this function operated as intended with HTTPS.

**Closed as not planned** 2024-11-07 01:57 UTC

**Comment by andrew-manger** [comment] 2025-01-12 19:54
I can confirm this is also broken on Safari

**Comment by pritpal-star** [comment] 2025-03-27 10:49
Still Facing this issue
