### ISSUE TITLE
PDF preview on Android

### ISSUE THREAD

**Issue by pierluigizagaria** [filebrowser/filebrowser#3237] opened 2024-05-19 18:58 UTC
**Description**
PDF cannot be opened Android devices.

**Expected behaviour**
View the pdf content like on web desktop.

**What is happening instead?**

<img src="https://github.com/filebrowser/filebrowser/assets/57801386/2a8bb367-77e4-45b9-b9f1-0415d450b871" height="400" />

**Additional context**
Problem already saw on other issue but all closed even tho the problem still persists.

**Comment by mradalbert** [comment] 2024-05-20 11:28
Duplicate of: https://github.com/filebrowser/filebrowser/issues/1201

**Comment by pierluigizagaria** [comment] 2024-05-20 11:32
Why is the #1201 closed? The issue still persists and no workaround are found

**Comment by mradalbert** [comment] 2024-05-20 12:25
Filevrowser doesn't render pdfs and relies on browser to do so. It is browser issue IMO.

**Comment by pierluigizagaria** [comment] 2024-05-20 12:41
Filebrowser has the preview feature for different kinds of file extensions that does not depend on the device browser. Could we manage pdf in the same way? So previews are always working regardless the browser?
Can we implement that If the browser does not support the file, automatically download it so chrome opens it directly?

**Closed as completed** 2024-06-25 01:48 UTC

**Comment by Mubelotix** [comment] 2024-08-24 14:22
Still an issue. This stale bot is infuriating
