### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by boscher** [filebrowser/filebrowser#585] opened 2018-12-24 14:00 UTC
**Description**
I try upload big file (1,5Gb) but this action throw internal server error

**Expected behaviour**
File downloaded

**What is happening instead?**
Listening on [::]:64084
2018/12/24 16:45:19 http: multiple response.WriteHeader calls
2018/12/24 16:45:19 /: 500 Internal Server Error
2018/12/24 16:45:19 write tcp [::1]:64084->[::1]:64137: wsasend: An existing connection was forcibly closed by the remote host.

**Additional context**

**How to reproduce?**
Just try upload big file

**Files**
I cant load this file. File is simple TXT and size equal or more than 1,5Gb

**Comment by hacdias** [comment] 2019-08-07 09:31
Can't reproduce. Are you using some web server like nginx, caddy or apache? Perhaps their limiting the upload size.

**Comment by hacdias** [comment] 2020-01-09 17:58
I'm closing this since this repository will be archived. Please read the information on the README for more information. Thanks for all your contributions!

**Closed as completed by hacdias** 2020-01-09 17:58 UTC
