### ISSUE TITLE
Feature request: large file multi-part upload

### ISSUE THREAD

**Issue by xlight** [filebrowser/filebrowser#1345] opened 2021-03-19 06:42 UTC
**Is your feature request related to a problem? Please describe.**
when I upload a very large file (10G+), there is many problem like nginx upload size limit , network not stable ,etc.

**Describe the solution you'd like**
implement a muli-part upload like S3.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_AbortMultipartUpload.html

**Comment by o1egl** [comment] 2021-03-19 16:40
duplicate of https://github.com/filebrowser/filebrowser/discussions/1182

**Closed as completed by o1egl** 2021-03-19 16:40 UTC
