### ISSUE TITLE
Use win command "mklink /d[/j]  target dir source dir" to create a dir link，this dir link is judged as a file

### ISSUE THREAD

**Issue by ladixiu** [filebrowser/filebrowser#1490] opened 2021-07-31 07:06 UTC
![image](https://user-images.githubusercontent.com/43605070/127731864-821c9e32-b59f-4fe9-addf-28415e4cfa09.png)

this is go io/fs problem

**Comment by ladixiu** [comment] 2021-07-31 07:14
root path
scope  path
 not surport multi
when has multi dir in diffrent path
i use win mklink to relate diffrent path to on dir

**Comment by o1egl** [comment] 2021-08-04 09:43
Duplicate of #1488

**Closed as completed by o1egl** 2021-08-04 09:43 UTC
