### ISSUE TITLE
setting recaptcha.host borks baseURL, setting baseurl sets recaptcha.host to google.

### ISSUE THREAD

**Issue by dkebler** [filebrowser/filebrowser#1779] opened 2022-01-19 01:40 UTC
**Description**
Weird one.
If I `filebrowser config set --recaptha.host` then baseURL is corrupted and I must (re)set `-b ""` or else my reverse proxy hangs.
on the flip side if I set --baseurl  then recaptcha.host is set to the default (google).  So basically I can't use other than google for captcha.

**Expected behaviour**
for the two config settings not to interfere with each other.

latest filebrowser running on ubuntu amd64 box.

**How to reproduce?**
set up a reverse proxy (caddy in my case)
set the recaptcha.host to other than google.
start filebrowser and use reverse proxy url,  site never loads
set baseurl "" , restart.  Site loads but recaptcha says "ERROR for site owner: Invalid site key"
cat the config....see that the recaptcha host is not what you set but google.com which explains why the invalid site key
say wtf.

filebrowser config set --auth.method=json --recaptcha.key $KEY --recaptcha.secret $SECRET  --recaptcha.host $HOST
```
Sign up:          false
Create User Dir:  false
Auth method:      json
Shell:              

Branding:
  Name:                    
  Files override:          
  Disable external links:  false
  Color:                   

Server:
  Log:           stdout
  Port:          11080
  Base URL:      
  Root:          /data
  Socket:        
  Address:       0.0.0.0
  TLS Cert:      
  TLS Key:       
  Exec Enabled:  false

Defaults:
  Scope:         /data/gpcca-files
  Locale:        en
  View mode:     mosaic
  Single Click:  false
  Commands:      
  Sorting:
    By:   
    Asc:  false
  Permissions:
    Admin:     false
    Execute:   true
    Create:    true
    Rename:    true
    Modify:    true
    Delete:    true
    Share:     true
    Download:  true

Auther configuration (raw):

{
  "recaptcha": {
    "host": "https://hcaptcha.com/siteverify",
    "key": "32f2a878-5d7c-442a-9813-4ac282b13cf3",
    "secret": "0xe28254F5e308Fb253aa9365486Db069a691790F2"
  }
}
```
despite not showing anything the baseurl is borked.

so run
./filebrowser config set -b ""
and surprise the recaptha.host is reset.
```
Sign up:          false
Create User Dir:  false
Auth method:      json
Shell:              

Branding:
  Name:                    
  Files override:          
  Disable external links:  false
  Color:                   

Server:
  Log:           stdout
  Port:          11080
  Base URL:      
  Root:          /data
  Socket:        
  Address:       0.0.0.0
  TLS Cert:      
  TLS Key:       
  Exec Enabled:  false

Defaults:
  Scope:         /data/gpcca-files
  Locale:        en
  View mode:     mosaic
  Single Click:  false
  Commands:      
  Sorting:
    By:   
    Asc:  false
  Permissions:
    Admin:     false
    Execute:   true
    Create:    true
    Rename:    true
    Modify:    true
    Delete:    true
    Share:     true
    Download:  true

Auther configuration (raw):

{
  "recaptcha": {
    "host": "https://www.google.com",
    "key": "32f2a878-5d7c-442a-9813-4ac282b13cf3",
    "secret": "0xe28254F5e308Fb253aa9365486Db069a691790F2"
  }
}

```

**Comment by ramiresviana** [comment] 2022-01-19 13:15
The problem is not directly related to the base url parameter, when using the `config set` command the recaptcha host is being redefined, this is an issue and should be fixed. FileBrowser only supports the reCAPTCHA provided by Google, using another service will not work.

**Closed as completed** 2022-09-14 02:13 UTC
