### ISSUE TITLE
"Copy" is available even if there's no folder to copy to

### ISSUE THREAD

**Issue by magikstm** [filebrowser/filebrowser#267] opened 2017-10-23 07:31 UTC
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?
Caddy v0.10.10 (non-commercial)
http.filemanager v1.3.6

Used on Windows 7 x64.
### 2. What is your entire Caddyfile?
```
:2015 {
	root F:/caddy-filemanager-test
	filemanager /admin ./admin {
		no_auth
	}
}
```

### 3. What are you trying to do?
Copy a file to another folder. (without a folder to copy to being available)

### 4. What did you expect to see?
The "Copy" option being greyed out or unavailable.

### 5. What did you see instead (give full error messages and/or log)?
The "Copy" option being available.

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Use the caddyfile above with at least one file that can be copied.

This issue could probably be labeled as an "enhancement" as it doesn't really hinder use.

**Comment by hacdias** [comment] 2017-10-29 13:18
Duplicate of #265: same cause.

**Closed as completed by hacdias** 2017-10-29 13:18 UTC
