### ISSUE TITLE
Upload events do not work.

### ISSUE THREAD

**Issue by mourisio** [filebrowser/filebrowser#2721] opened 2023-09-18 09:16 UTC
**Description**
I use the latest version of filebrowser - 2.25.0. When I try to run commands from built-in command runner, using after upload or before upload events, it just does not work. But when I create new file via filebrowser interface it works. this is the script I am trying to run for test purpose - /bin/sh -c 'echo "File  is uploaded." >> /home/test.txt'

**Expected behaviour**
Run script after or before uploading a file.

**What is happening instead?**
Script does not work. it only works when I create a file via web interface.

**Additional context**
The error was not occurred in v2.23.0 or less. I have the same problem in higher versions (I tested all of them).

**How to reproduce?**
Go to command runner in web interface.
write script in before or after upload event tab.
upload a file.

**Comment by kafeinnet** [comment] 2023-09-29 06:42
Duplicate of #2626 I think.

**Closed as completed** 2023-11-05 01:46 UTC
