### ISSUE TITLE
能不能开发一个分享管理的。整体查看文件分享情况。

### ISSUE THREAD

**Issue by qigj** [filebrowser/filebrowser#1150] opened 2020-11-18 02:46 UTC
**Is your feature request related to a problem? Please describe.**
Add a clear and concise description of what the problem is. E.g. *I'm always frustrated when [...]*

**Describe the solution you'd like**
Add a clear and concise description of what you want to happen.

**Describe alternatives you've considered**
Add a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

**Comment by o1egl** [comment] 2020-11-18 09:37
Can you please translate it into English?

**Comment by Waitung** [comment] 2020-11-19 08:33
#1000

**Comment by o1egl** [comment] 2020-11-19 08:58
Duplicate of #1000

**Closed as completed by o1egl** 2020-11-19 08:58 UTC
