### ISSUE TITLE
FR: Please support folder upload

### ISSUE THREAD

**Issue by wenerme** [filebrowser/filebrowser#375] opened 2018-03-08 03:35 UTC
### 3. What are you trying to do?

I want to upload a folder

### 4. What did you expect to see?

Upload can select folder

### 5. What did you see instead (give full error messages and/or log)?

Upload can only select file

**Comment by hacdias** [comment] 2018-03-11 10:46
Duplicate of #244. Could you up vote it there please @wenerme? 😄

**Closed as completed by hacdias** 2018-03-11 10:46 UTC
