### ISSUE TITLE
Filebrowser hangs when attempting to change sort order

### ISSUE THREAD

**Issue by obermotz** [filebrowser/filebrowser#2772] opened 2023-10-18 12:17 UTC
**Description**
Whenever I try to change the sorting order of a displayed folder, the current filebrowser session hangs. A logout/login combo helps.

**Expected behaviour**
File sorting order changes as expected.

**What is happening instead?**
This message is displayed indefinitely:
![image](https://github.com/filebrowser/filebrowser/assets/22054677/83efbca4-bcea-4e4b-940e-d30cd56d3490)

**Additional context**
Running FB 2.25.0 in docker.

**How to reproduce?**
All you have to do is just to try to change the file sorting order by clicking on one of the column headers.

**Comment by blue212121** [comment] 2023-10-19 20:23
same issue happening for me on version 2.25.0 running in docker

**Comment by Mysterius** [comment] 2023-10-22 10:02
Yep, sorting is broken, as well as user profiles.
Probable duplicate of #2708 and #2748 because symptoms are the same.

**Comment by clement-jiao** [comment] 2023-10-25 11:56
maybe it's a bug in this version, didn't have this problem on 2.24.2

**Comment by blue212121** [comment] 2023-10-25 12:15
> maybe it's a bug in this version, didn't have this problem on 2.24.2

yes, i installed 2.24.2 over the weekend, sorting works without issues in that version

**Comment by obermotz** [comment] 2023-10-25 14:35
> > maybe it's a bug in this version, didn't have this problem on 2.24.2
> 
> yes, i installed 2.24.2 over the weekend, sorting works without issues in that version

Can confirm, downgraded to 2.24.2, no issues with sorting.

**Comment by o1egl** [comment] 2023-11-02 21:25
Fixed in https://github.com/filebrowser/filebrowser/pull/2792

**Closed as completed by o1egl** 2023-11-02 21:25 UTC
Labels: bug
