### ISSUE TITLE
Request for Sharing Multiple Files or Folder Sharing Preview

### ISSUE THREAD

**Issue by if1y** [filebrowser/filebrowser#1141] opened 2020-11-09 10:17 UTC
### Is your feature request related to a problem? Please describe
I wanna share some files with my friends.
Firstly I put those files in a folder, and create a share link for the folder. But I found **it is only permitted to download the whole folder** within a `zip` file. That makes people **unable to know what files are in the folder, and unable to preview them, but only to download and see**.
Therefore I tried to enable the multiple selection mode and select all the files within the folder. But **no share button is given when multiple files are selected**.

### Describe the solution you'd like
Just provide with multiple files sharing, or folder sharing preview.
**Both of them are okay**.
Thank you!

**Comment by o1egl** [comment] 2020-11-09 13:47
Thank you for your request. That feature is already implemented and will be included in the next release

**Comment by o1egl** [comment] 2020-11-09 13:48
Duplicate of https://github.com/filebrowser/filebrowser/issues/1023

**Closed as completed by o1egl** 2020-11-09 13:48 UTC

**Comment by if1y** [comment] 2020-11-27 12:21
Just tried 2.10.0, but only able to view files in folder.
Hope can choose any one or severals before downloading~
