### ISSUE TITLE
 can't save a file in new created folder (Permission denied )

### ISSUE THREAD

**Issue by Bitti09** [filebrowser/filebrowser#190] opened 2017-08-05 18:30 UTC
New created folder gets  drw-r--r-- permissions
Creating a file inside the folder via filemanager results in an permission denied error.
Changing permissions manually to drwxr--r-- resolvs the error.

**Comment by hacdias** [comment] 2017-08-05 20:25
Folders are created with 0666 permissions... you can see the [source here](https://github.com/hacdias/filemanager/blob/master/resource.go#L167). I can't see where the problem is now... I'll try to reproduce this.

**Comment by Bitti09** [comment] 2017-08-05 20:48
note: i've tested it on a freshl downloaded caddy with filemanager as a plugin today  and got the error.
Me too doesn't sees the reason why the caddy filemanager plugin uses 644 as permission

**Comment by Equim-chan** [comment] 2017-08-11 02:08
+1
In my case (linux x64, standalone filemanager built via `go get` at 7ee721a), new created folder gets `drw-rw-r--`(664).

Without `rwx` permission, the folder is not actually "writable", and can't even be accessed by `cd`.

![](https://i.stack.imgur.com/mZ6qv.png)
Ref: https://unix.stackexchange.com/questions/21251/execute-vs-read-bit-how-do-directory-permissions-in-linux-work
Hopefully it helps.

**Comment by hacdias** [comment] 2017-08-11 07:07
I have 0666 for the default permissions now. What do you think I should change it for? 0766?

**Comment by Equim-chan** [comment] 2017-08-11 07:41
Hmm, the default permissions set for folders created by `mkdir` on my machine is 776. This should be fine.

**Comment by hacdias** [comment] 2017-08-11 10:57
I pushed a fix for this (changed to 0776) and it will be out when 1.2.0 is released (today or tomorrow).

**Closed as completed by hacdias** 2017-08-11 10:57 UTC
