### ISSUE TITLE
Add Leaps Operational Transform For Collaborative Editing

### ISSUE THREAD

**Issue by faddat** [filebrowser/filebrowser#42] opened 2016-02-09 03:58 UTC
I'm implementing this by just having leaps edit the text files that are used by Hugo-Caddy to generate pages from...... but it could be even greater than that, ya know?

https://github.com/Jeffail/leaps

**Comment by hacdias** [comment] 2016-02-09 07:59
I see (more or less). But right now we can only support one user. How would this be useful?

_P.S.: I don't know if you're using the version on this repository or the version that can be downloaded at caddyserver.com. I recommend you to build it from source to try out the new version which is very less buggy._

**Comment by faddat** [comment] 2016-02-09 10:09
Gotcha.  If it helps, I think that leaps has user management of some sorts.  I haven't gotten pro-level with its config file yet, however...

**Comment by hacdias** [comment] 2016-02-09 11:03
I'll leave this issue open because it can be something to try in the future. If you want to do so, go on and try. :+1: 

Right now I think there is a new auth plugin for caddy in the kiln so I'll wait for that. But you can test it!

**Comment by faddat** [comment] 2016-02-09 11:07
Do you mind letting me know how to try?  Sorry, I keep taking baby steps towards golang but am not quite there yet.  I learned today from someone else it is very easy to integrate golang applications, but..... _knowledge peters out here_

**Comment by hacdias** [comment] 2016-02-09 11:12
The problem is that I don't even know how to try it. I would have to investigate the code of Leaps and then see how could it be integrated with caddy-hugo. Anyway, I recommend you to read this [article](https://golang.org/doc/effective_go.html) which may help you :D You'll get it!

**Comment by faddat** [comment] 2016-02-13 20:18
It was a really great article, by the way-- thank you!

**Comment by hacdias** [comment] 2016-02-13 20:25
You're welcome!

**Comment by faddat** [comment] 2016-02-18 06:04
Okay, so: leaps uses JavaScript text areas to serve collaborative editing sessions.  The code for making one is quite simple.  Can you point out where caddy-hugo has its text areas?   

I will give this a shot myself now.  If it works,I will send a pr your way.

**Comment by hacdias** [comment] 2016-02-18 07:45
The main contente text areas are the ones with `name="content"` like [here](https://github.com/hacdias/caddy-hugo/blob/master/templates/editor.tmpl#L43) and [here](https://github.com/hacdias/caddy-hugo/blob/master/templates/editor.tmpl#L22). 

Just for reference, you've to know that those text areas are not visible, they're hidden. What is shown is the Ace Editor (see [here](https://github.com/hacdias/caddy-hugo/blob/master/assets/src/js/editor.js#L16)).

Go on and try it! :D

**Comment by faddat** [comment] 2016-02-22 13:15
I'm hitting some difficulty in what I think are the last steps.  

```
root@fuzzbox:~/hugo-semantic-homepage-starter# caddydev --source /root/caddy-hugo hugo
Caddy source not found. Fetching... done.
process killed: go get took too long

---- COMMAND: go get -d caddyaddon
---- 
---- package github.com/hacdias/caddy-hugo/assets: no buildable Go source files in /tmp/caddydev744094139/src/github.com/hacdias/caddy-hugo/assets

```

**Comment by hacdias** [comment] 2016-02-22 20:00
Execute first `cd /root/caddy-hugo & go generate`.

**Comment by faddat** [comment] 2016-02-22 21:35
I think I had, but let me try that.  I _think_ I fillowed your directions for developers exactly.  But maybe I didn't ;).

**Comment by hacdias** [comment] 2016-03-05 14:10
@faddat I will close this issue for now because I think `caddy-hugo` doesn't need this heavy app right now. But I'll leave a reference to #39. Maybe in the future :)

**Closed as completed by hacdias** 2016-03-05 14:10 UTC
