### ISSUE TITLE
Page freeze after changing settings

### ISSUE THREAD

**Issue by luke6464** [filebrowser/filebrowser#2743] opened 2023-10-03 09:48 UTC
HI,
I would like to report the following bug...
when I go to the settings tab of any user, even an administrator, and change one of the settings for example "Set exact date format" after confirming the change by returning to any of the other tabs for example "My files" or other the page freezes loading and you need to refresh the browser to unlock it ... but after the refresh the Login screen reappears ...
see all the attached screenshots...
How can I solve it? ...
System: Raspberry Pi4
File Browser Version: 2.25
Tanks
![screenshot_20231003_111040](https://github.com/filebrowser/filebrowser/assets/3793119/4d4ec31a-e953-443f-853c-8bb4821aa70b)
![screenshot_20231003_111154](https://github.com/filebrowser/filebrowser/assets/3793119/8ee9bfe9-54ec-4910-a3b6-bbf510a25340)
![screenshot_20231003_111308](https://github.com/filebrowser/filebrowser/assets/3793119/a3c56b3b-1f5a-42f1-9687-7595082aa88e)
![screenshot_20231003_111402](https://github.com/filebrowser/filebrowser/assets/3793119/c312449b-4836-4b8d-b898-8f4a9f1152c3)

**Comment by Mysterius** [comment] 2023-10-06 17:26
Probably a duplicate of #2708  and #2724 
It's a real problem atm because it feels like File Browser is unstable. It's not, it's probably just a small bug somewhere that is affecting two systems (the sorting, and changing settings the the user panel).

**Comment by o1egl** [comment] 2023-11-02 21:32
Fixed

**Closed as completed by o1egl** 2023-11-02 21:32 UTC
