### ISSUE TITLE
Can't log in with basicauth to hugo plugin

### ISSUE THREAD

**Issue by skyfaller** [filebrowser/filebrowser#259] opened 2017-10-21 13:43 UTC
### 1. Have you downloaded File Manager from caddyserver.com? If yes, when have you done that? If no, and you are running a custom build, which is the revision of File Manager's repository?
Caddy version: Caddy 0.10.10 (non-commercial use only)
Hugo version: Hugo Static Site Generator v0.30.2 linux/amd64 BuildDate: 2017-10-19T07:34:27-04:00

### 2. What is your entire Caddyfile?
```
nelson.pavlosky.net {
  root /srv/pavlosky.net/nelson/public  # the folder where Hugo generates the website
  hugo /srv/pavlosky.net/nelson /admin # enable the admin panel
  basicauth /admin username password
  expires {
    match .png$ 1y # expires png files after one year
    match .jpg$ 1y # expires jpg files after one year
    match .html$ 5i30s # expires html files after 5 minutes 30 seconds
    match .css  1y # expires css files
  }
  gzip
  errors {
    404 404.html # Not Found
  }
}
```

### 3. What are you trying to do?
I want to log into the Caddy Hugo/filemanager plugin.

### 4. What did you expect to see?
Upon entering the correct username and password, I should see the filemanager.

### 5. What did you see instead (give full error messages and/or log)?
Instead I just keep on seeing the user/pass login screen again, as if I had the wrong password.

Basicauth works without the hugo plugin, if I take out the "hugo" line I am able to log in with the correct user/pass and see a pretty 404 message.
The hugo plugin also works without basicauth, if I disable authentication entirely with no_auth, I am able to log in and see the file manager.
This all worked fine a couple months ago, then at some point some update to caddy or hugo broke it.

### 6. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Dunno. I was referred here from https://caddy.community/t/cant-log-in-with-basicauth/2865/3

**Comment by magikstm** [comment] 2017-10-21 23:00
I tested locally on a Windows 7 x64 laptop and I can confirm this issue.

It can be reproduced minimally with this Caddyfile:
:2015 {
	root C:/caddy-filemanager-test  # the folder where Hugo generates the website
	hugo /admin /admin # enable the admin panel
	basicauth /admin username password
}

I can also confirm these behavior:
1) If I don't try a "user" & "password" and click "Cancel" I get "401 Unauthorized"
2) If I enter the right "user" & "password" then click "Ok" I seem to get a loop that requests credentials
3) If I enter the right "user" & "password" then click "Cancel" I see the FileManager

The issue seems to be the loop requesting credentials after a successful "user" & "password".

**Comment by magikstm** [comment] 2017-10-21 23:18
I can confirm the same behavior with filemanager.

With this minimal caddyfile:
:2015 {
	root C:/caddy-filemanager-test
	filemanager /admin
	basicauth /admin username password
}

**Comment by hacdias** [comment] 2017-10-22 22:32
Hello!

That way, you're configuring Hugo's/Filemanager's own auth system as well as basicauth and they're colliding which will make neither of them work!

You could try the following:

```
nelson.pavlosky.net {
  root /srv/pavlosky.net/nelson/public  # the folder where Hugo generates the website
  hugo /srv/pavlosky.net/nelson /admin {
     no_auth
  }
  basicauth /admin username password
  expires {
    match .png$ 1y # expires png files after one year
    match .jpg$ 1y # expires jpg files after one year
    match .html$ 5i30s # expires html files after 5 minutes 30 seconds
    match .css  1y # expires css files
  }
  gzip
  errors {
    404 404.html # Not Found
  }
}
```

Hope it works! 😄

**Comment by magikstm** [comment] 2017-10-23 06:45
I tested the [no_auth] parameter with filemanager and hugo and it worked with my minimal tests.

It'll probably resolve OP's issue.

I would suggest adding a few lines in the docs here about this possible issue with other auth plugins:
https://henriquedias.com/filemanager/caddy/

**Comment by skyfaller** [comment] 2017-10-26 15:04
Thank you folks, hacdias's suggested Caddyfile did indeed fix my problem.

I'm not married to basicauth though, I'd be happy to use Filemanager's own auth system. How do you use it? More specifically, how do you set your username + password? I see no information on how to do that at https://henriquedias.com/filemanager/caddy/ . It says I should create a new user, but offers no info on how to do that.

**Comment by hacdias** [comment] 2017-10-26 20:18
Hey @skyfaller! By default the credentials are admin/admin. If you want to create a new user, or change your current password/username, just to go the Settings. I know you'll find how to do the rest there 😄

**Comment by hacdias** [comment] 2017-10-26 20:29
I will just close this issue since it's main subject is solved. I need a bit of time to clean every issue up and solve every problem 😞

**Closed as completed by hacdias** 2017-10-26 20:29 UTC
